import { describe, it, expect } from "vitest";
import { generateMarkdownReport, generateJsonReport } from "../src/report.js";
import type { ComparisonResult } from "../src/compare.js";

describe("generateMarkdownReport", () => {
  const result: ComparisonResult = {
    assets: [
      {
        name: "main.js",
        type: "js",
        beforeSize: 142300,
        afterSize: 148700,
        diff: 6400,
        diffPercent: 4.5,
        status: "changed",
      },
      {
        name: "vendor.js",
        type: "js",
        beforeSize: 89200,
        afterSize: 89200,
        diff: 0,
        diffPercent: 0,
        status: "unchanged",
      },
      {
        name: "new-chunk.js",
        type: "js",
        beforeSize: null,
        afterSize: 24680,
        diff: 24680,
        diffPercent: null,
        status: "added",
      },
    ],
    totalBefore: 231500,
    totalAfter: 262580,
    totalDiff: 31080,
    totalDiffPercent: 13.4,
    addedCount: 1,
    removedCount: 0,
    changedCount: 1,
  };

  it("should include Bundle Badger header", () => {
    const report = generateMarkdownReport(result);
    expect(report).toContain("🦡 Bundle Badger Report");
  });

  it("should include table with before/after columns", () => {
    const report = generateMarkdownReport(result);

    expect(report).toContain("| File | Before | After | Diff |");
    expect(report).toContain("`main.js`");
    expect(report).toContain("142 kB");
    expect(report).toContain("149 kB");
  });

  it("should show total summary", () => {
    const report = generateMarkdownReport(result);

    expect(report).toContain("**Total:**");
    expect(report).toContain("232 kB");
    expect(report).toContain("263 kB");
  });

  it("should include status indicators", () => {
    const report = generateMarkdownReport(result);

    // Should have colored indicators
    expect(report).toMatch(/🔴|🟠|🟡|🟢|✅|🆕|🗑️/);
  });

  it("should include change count", () => {
    const report = generateMarkdownReport(result);

    expect(report).toContain("1 changed");
    expect(report).toContain("1 added");
  });

  it("should include footer", () => {
    const report = generateMarkdownReport(result);

    expect(report).toContain("Generated by [Bundle Badger]");
  });

  it("should respect changedOnly option", () => {
    const report = generateMarkdownReport(result, { changedOnly: true });

    expect(report).toContain("main.js");
    expect(report).toContain("new-chunk.js");
    expect(report).not.toContain("vendor.js");
  });

  it("should respect maxAssets option", () => {
    const manyAssets: ComparisonResult = {
      ...result,
      assets: Array(30)
        .fill(null)
        .map((_, i) => ({
          name: `chunk-${i}.js`,
          type: "js" as const,
          beforeSize: 1000 + i,
          afterSize: 1100 + i,
          diff: 100,
          diffPercent: 10,
          status: "changed" as const,
        })),
    };

    const report = generateMarkdownReport(manyAssets, { maxAssets: 5 });

    expect(report).toContain("... and 25 more");
  });
});

describe("generateMarkdownReport without baseline", () => {
  const result: ComparisonResult = {
    assets: [
      {
        name: "main.js",
        type: "js",
        beforeSize: null,
        afterSize: 100000,
        diff: 100000,
        diffPercent: null,
        status: "added",
      },
    ],
    totalBefore: 0,
    totalAfter: 100000,
    totalDiff: 100000,
    totalDiffPercent: 0,
    addedCount: 1,
    removedCount: 0,
    changedCount: 0,
  };

  it("should show only size column without baseline", () => {
    const report = generateMarkdownReport(result);

    expect(report).toContain("| File | Size |");
    expect(report).not.toContain("Before");
    expect(report).not.toContain("After");
  });

  it("should show simple total", () => {
    const report = generateMarkdownReport(result);

    expect(report).toContain("**Total:** 100 kB");
    expect(report).not.toContain("→");
  });
});

describe("generateJsonReport", () => {
  const result: ComparisonResult = {
    assets: [
      {
        name: "main.js",
        type: "js",
        beforeSize: 100000,
        afterSize: 105000,
        diff: 5000,
        diffPercent: 5,
        status: "changed",
      },
    ],
    totalBefore: 100000,
    totalAfter: 105000,
    totalDiff: 5000,
    totalDiffPercent: 5,
    addedCount: 0,
    removedCount: 0,
    changedCount: 1,
  };

  it("should return valid JSON", () => {
    const report = generateJsonReport(result);
    const parsed = JSON.parse(report);

    expect(parsed.assets).toHaveLength(1);
    expect(parsed.summary.totalDiff).toBe(5000);
  });

  it("should include all asset details", () => {
    const report = generateJsonReport(result);
    const parsed = JSON.parse(report);

    expect(parsed.assets[0].name).toBe("main.js");
    expect(parsed.assets[0].beforeSize).toBe(100000);
    expect(parsed.assets[0].afterSize).toBe(105000);
    expect(parsed.assets[0].status).toBe("changed");
  });
});
