import type { ComparisonResult, AssetComparison } from "./compare.js";
import { formatBytes, formatDiff, formatPercent } from "./utils.js";

export interface ReportOptions {
  /** Maximum number of assets to show in detail (default: 20) */
  maxAssets?: number;
  /** Show only changed files (default: false) */
  changedOnly?: boolean;
  /** Include status indicators (default: true) */
  showStatus?: boolean;
}

/**
 * Generate markdown report from comparison result
 */
export function generateMarkdownReport(
  result: ComparisonResult,
  options: ReportOptions = {}
): string {
  const { maxAssets = 20, changedOnly = false, showStatus = true } = options;

  const lines: string[] = [];

  lines.push("## 🦡 Bundle Badger Report");
  lines.push("");

  // Filter assets if needed
  let assetsToShow = result.assets;
  if (changedOnly) {
    assetsToShow = assetsToShow.filter((a) => a.status !== "unchanged");
  }

  const hasBaseline = result.totalBefore > 0;

  if (assetsToShow.length === 0) {
    lines.push("No bundle changes detected.");
    lines.push("");
  } else {
    // Generate table
    if (hasBaseline) {
      lines.push("| File | Before | After | Diff |");
      lines.push("| ---- | -----: | ----: | ---: |");
    } else {
      lines.push("| File | Size |");
      lines.push("| ---- | ---: |");
    }

    const shownAssets = assetsToShow.slice(0, maxAssets);
    const hiddenCount = assetsToShow.length - shownAssets.length;

    for (const asset of shownAssets) {
      lines.push(formatAssetRow(asset, hasBaseline, showStatus));
    }

    if (hiddenCount > 0) {
      if (hasBaseline) {
        lines.push(`| ... and ${hiddenCount} more | | | |`);
      } else {
        lines.push(`| ... and ${hiddenCount} more | |`);
      }
    }

    lines.push("");
  }

  // Summary
  if (hasBaseline) {
    const status = getOverallStatus(result.totalDiffPercent);
    lines.push(
      `**Total:** ${formatBytes(result.totalBefore)} → ${formatBytes(result.totalAfter)} ` +
        `(${formatDiff(result.totalDiff)} / ${formatPercent(result.totalDiffPercent)}) ${status}`
    );
  } else {
    lines.push(`**Total:** ${formatBytes(result.totalAfter)}`);
  }

  // Change summary
  if (hasBaseline) {
    const changes: string[] = [];
    if (result.changedCount > 0) {
      changes.push(`${result.changedCount} changed`);
    }
    if (result.addedCount > 0) {
      changes.push(`${result.addedCount} added`);
    }
    if (result.removedCount > 0) {
      changes.push(`${result.removedCount} removed`);
    }

    if (changes.length > 0) {
      lines.push("");
      lines.push(`_${changes.join(", ")}_`);
    }
  }

  lines.push("");
  lines.push("---");
  lines.push("");
  lines.push("_Generated by [Bundle Badger](https://gitlab.com/mbuga/bundle-badger)_");

  return lines.join("\n");
}

function formatAssetRow(
  asset: AssetComparison,
  hasBaseline: boolean,
  showStatus: boolean
): string {
  const name = `\`${asset.name}\``;

  if (!hasBaseline) {
    return `| ${name} | ${formatBytes(asset.afterSize ?? 0)} |`;
  }

  const before =
    asset.beforeSize !== null ? formatBytes(asset.beforeSize) : "-";
  const after = asset.afterSize !== null ? formatBytes(asset.afterSize) : "-";

  let diffStr: string;
  if (asset.status === "added") {
    diffStr = `+${formatBytes(asset.afterSize ?? 0)} (new)`;
  } else if (asset.status === "removed") {
    diffStr = `${formatDiff(asset.diff)} (removed)`;
  } else if (asset.diff === 0) {
    diffStr = "0";
  } else {
    diffStr = `${formatDiff(asset.diff)}`;
    if (asset.diffPercent !== null) {
      diffStr += ` (${formatPercent(asset.diffPercent)})`;
    }
  }

  if (showStatus) {
    diffStr += ` ${getAssetStatus(asset)}`;
  }

  return `| ${name} | ${before} | ${after} | ${diffStr} |`;
}

function getAssetStatus(asset: AssetComparison): string {
  if (asset.status === "added") return "🆕";
  if (asset.status === "removed") return "🗑️";
  if (asset.diff === 0) return "✅";
  if (asset.diff > 0) {
    // Size increased
    const percent = asset.diffPercent ?? 0;
    if (percent > 10) return "🔴";
    if (percent > 5) return "🟠";
    return "🟡";
  }
  // Size decreased
  return "🟢";
}

function getOverallStatus(diffPercent: number): string {
  if (diffPercent === 0) return "✅";
  if (diffPercent < 0) return "🟢";
  if (diffPercent > 10) return "🔴";
  if (diffPercent > 5) return "🟠";
  return "🟡";
}

/**
 * Generate JSON report from comparison result
 */
export function generateJsonReport(result: ComparisonResult): string {
  return JSON.stringify(
    {
      assets: result.assets,
      summary: {
        totalBefore: result.totalBefore,
        totalAfter: result.totalAfter,
        totalDiff: result.totalDiff,
        totalDiffPercent: result.totalDiffPercent,
        addedCount: result.addedCount,
        removedCount: result.removedCount,
        changedCount: result.changedCount,
      },
    },
    null,
    2
  );
}
